version: '3'

services:
  postgres:
    image: postgres
    container_name: 'technology-solutions-postgres'
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    networks:
      - postgres-network
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - ${DATABASE_PORT}:5432

networks:
  postgres-network:

volumes:
  postgres-data:
  rabbitmq-data:
